### ISSUE TITLE
error message after entering p in autoplotly example code

### ISSUE THREAD

**Issue by sfd99** [terrytangyuan/autoplotly#2]
Hi Terry! -

Following your blog post code example,
I entered:

**> p <- autoplotly(prcomp(iris[c(1, 2, 3, 4)]), data = iris,
colour = 'Species', frame = TRUE)**

# OK !..
**> class(p)**
[1] "plotly" "htmlwidget"

# but... I get an error message when I next enter:
**>  p**
Error in attr %in% names(Schema$traces[[x]]$attributes) :
cannot open file '~/R/i686-pc-linux-gnu-library/3.4/plotly/R/sysdata.rdb': No such file or directory
In addition: Warning message:
In attr %in% names(Schema$traces[[x]]$attributes) :
restarting interrupted promise evaluation

What's wrong?

SFdisqus
using latest Rstudio, R,
under Ubuntu LINUX 14.04 LTS 32-bits.

PKGS installed
and loaded in the Rstudio Workspace:
1 - autoplotly GIT dev version: v 0.1.1

2 - plotly    v 4.7.1.9000,

3 - ggplot2 v  2.2.1.9000,

4 - ggfortify v 0.4.2

**Comment by terrytangyuan** [comment]
Could you try the suggestion by the second comment of this issue: https://github.com/gertstulp/ggplotgui/issues/3?

**Comment by terrytangyuan** [comment]
Also try run the example on this page: https://www.rdocumentation.org/packages/plotly/versions/4.7.1/topics/ggplotly
