### ISSUE TITLE
package vignette from blog post?

### ISSUE THREAD

**Issue by corybrunson** [terrytangyuan/autoplotly#3]
The [blog post](https://terrytangyuan.github.io/2018/02/12/autoplotly-intro/) linked in the README provides a very helpful intro to the package and its intended usage. I suspect, especially since the package is on CRAN, that many R users would seek guidance from a vignette and miss the links to this resource (`DESCRIPTION` -> GitHub repo -> blog post). Could the blog post be repurposed into a package vignette?

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/657)._

**Comment by terrytangyuan** [comment]
Thanks for pointing out! One problem with package vignette is that we cannot render interactive plots on CRAN. I think I'll just add the article as vignette with `eval = FALSE` then. Let me know what you think.

**Comment by corybrunson** [comment]
Oh, that's a point i hadn't considered. Your suggestion sounds right—i'll take a look when it's ready (or on an experimental branch). Thanks!
